title: Play Swipe Studios Homepage
page-top-title: Play Swipe Studios
top-section-bg-text: Computer Science
home-subtitle: Test
copyright-text: '&copy; Play Swipe Studios 2023-2024. All Rights Reserved.'
